spring:
  datasource:
    url: ${AWS_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000