spring:
  datasource:
    url: ${AWS_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client_id: ${KAKAO_REST_API_KEY}ㅣ
            redirect_uri: ${KAKAO_REDIRECT_URI}
            client-secret: ${KAKAO_SECRET_KEY}
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    root: INFO #
    com.umc7.ZIC: INFO #
    org.springframework.web: INFO
    org.springframework.security: INFO #
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO